{
 "title": "BatchProcessing",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "name",
    "query": "label_values(job:slo_definition:none{template=\"BatchProcessingSLO\"}, name)"
   },
   { "name": "interval", "label": "interval", "query": "1m,5m,15m" }
  ]
 },
 "panels": [
  {
   "title": "SLOs",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max without (cluster, context) (\n  job:slo_definition:none{name=\"$name\"} * on(name) group_right(budget) (\n    job:slo_error:ratio1d / on (name) group_left() job:slo_error_budget:ratio\n  )\n)"
    },
    {
     "expr": "max without (cluster, context) (\n  job:slo_definition:none{name=\"$name\"} * on(name) group_right(budget) (\n    job:slo_error:ratio7d / on (name) group_left() job:slo_error_budget:ratio\n  )\n)"
    },
    {
     "expr": "max without (cluster, context) (\n  job:slo_definition:none{name=\"$name\"} * on(name) group_right(budget) (\n    job:slo_error:ratio28d / on (name) group_left() job:slo_error_budget:ratio\n  )\n)"
    }
   ]
  },
  {
   "title": "Error budget remaining 28d",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_min(1 - (\n  max without (cluster, context) (\n    job:slo_definition:none{name=\"$name\", template=\"BatchProcessingSLO\"} * on(name) group_right(budget) (\n      job:slo_error:ratio28d / on (name) group_left() job:slo_error_budget:ratio\n    )\n  )\n), 0)",
     "legendFormat": "{{ namespace }} {{ release }}"
    }
   ]
  },
  {
   "title": "job:slo_batch_volume:max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:slo_batch_volume:max{name=\"$name\"}",
     "legendFormat": "{{ namespace }}/{{ release }}"
    }
   ]
  },
  {
   "title": "job:slo_batch_throughput_target:max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "job:slo_batch_throughput_target:max{name=\"$name\"}",
     "legendFormat": "{{ namespace }}/{{ release }}"
    }
   ]
  },
  {
   "title": "job:slo_batch_throughput:interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:slo_batch_throughput:interval{name=\"$name\"}",
     "legendFormat": "{{ namespace }}/{{ release }}"
    }
   ]
  },
  {
   "title": "job:slo_batch_error:interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "job:slo_batch_error:interval{name=\"$name\"}",
     "legendFormat": "{{ namespace }}/{{ release }}"
    }
   ]
  }
 ]
}