{
 "title": "ErrorRate",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "name",
    "query": "label_values(job:slo_definition:none{template=\"ErrorRateSLO\"}, name)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m, 30m, 1h, 2h, 6h, 1d, 3d, 7d, 28d"
   }
  ]
 },
 "panels": [
  {
   "title": "SLOs",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max without (cluster, context) (\n  job:slo_definition:none{name=\"$name\"} * on(name) group_right(budget) (\n    job:slo_error:ratio1d / on (name) group_left() job:slo_error_budget:ratio\n  )\n)"
    },
    {
     "expr": "max without (cluster, context) (\n  job:slo_definition:none{name=\"$name\"} * on(name) group_right(budget) (\n    job:slo_error:ratio7d / on (name) group_left() job:slo_error_budget:ratio\n  )\n)"
    },
    {
     "expr": "max without (cluster, context) (\n  job:slo_definition:none{name=\"$name\"} * on(name) group_right(budget) (\n    job:slo_error:ratio28d / on (name) group_left() job:slo_error_budget:ratio\n  )\n)"
    }
   ]
  },
  {
   "title": "Error budget remaining 28d",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_min(1 - (\n  max without (cluster, context) (\n    job:slo_definition:none{name=\"$name\", template=\"ErrorRateSLO\"} * on(name) group_right(budget) (\n      job:slo_error:ratio28d / on (name) group_left() job:slo_error_budget:ratio\n    )\n  )\n), 0)",
     "legendFormat": "{{ namespace }}/{{ release }}"
    }
   ]
  },
  {
   "title": "job:slo_error:ratio$interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "job:slo_error:ratio$interval{name=\"$name\"}",
     "legendFormat": "{{ namespace }}/{{ release }}"
    }
   ]
  },
  {
   "title": "job:slo_error_rate_total:rate$interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "job:slo_error_rate_total:rate$interval{name=\"$name\"}",
     "legendFormat": "{{ namespace }}/{{ release }}"
    }
   ]
  },
  {
   "title": "job:slo_error_rate_errors:rate$interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "job:slo_error_rate_errors:rate$interval{name=\"$name\"}",
     "legendFormat": "{{ namespace }}/{{ release }}"
    }
   ]
  }
 ]
}