name: test

on: push

jobs:
  promtool:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3
          with:
            go-version: 1.14.5
        - name: promtool check rules
          run: |
            curl --connect-timeout 15 --retry 3 -sfL \
              https://github.com/prometheus/prometheus/releases/download/v2.20.1/prometheus-2.20.1.linux-amd64.tar.gz \
              | tar --strip-components=1 -xzf - prometheus-2.20.1.linux-amd64/promtool \
            && ./promtool check rules *-rules.yaml
